(in-package :junker)

(defvar *menu*)
(setf *menu* '(("Terminal" . "exec kitty")
               ("Editor" . "exec featherpad")
               ("Calc" . "app-calc")
               ("TaskManager" . "app-taskmanager")
               ("Krusader" . "exec krusader")
               ("Workrave Break" . "workrave-brake")
               ("💼	Work >" . (
                               ("SSH terminal" . "app-kitty-ssh")
                               ("Emacs" . "app-emacs")
                               ("DBeaver" . "exec dbeaver")
                               ("Linguist" . "exec linguist")
                               ("Redmine" . "exec /opt/Redmine-linux-x64/Redmine")
                               ("QOwnNotes" . "app-qownnotes")))
               ("🌍	Inet >" . (("Firefox" . "app-firefox")
                               ("Chromium" . "exec chromium --use-vulkan --enable-features=Vulkan")
                               ("Telegram" . "app-telegram")
                               ("Mail" . "app-mail")
                               ("RSS" . "app-rss")
                               ("Tor browser" . "exec torbrowser-launcher")
                               ("LibreWolf" . "exec librewolf")
                               ("Torrent" . "app-qbittorrent")
                               ("Skype" . "exec skypeforlinux")
                               ("Nuclear (music)" . "exec nuclear --no-sandbox")))
               ("🧰	Utils >" . (("Screenshot" . "exec hotshots")
                                ("QR Code" . "exec qtqr")
                                ("KeePassXC" . "app-keepassxc")))
               ("🔧	System >" . (("Start all" . "j-start-all")
                                 ("3840x2160" . "exec xrandr -s 3840x2160 --output DP-2 --mode 3840x2160 --rate 60")
                                 ("1920x1080" . "exec xrandr -s 1920x1080")
                                 ("Lock screen" . "exec loginctl lock-session")
                                 ("SystemDGenie" . "exec gksudo systemdgenie")))
               ("🚪	Exit >" . (("Reboot" . "exec systemctl reboot")
                               ("Poweroff" . "exec systemctl poweroff")))))

(defcommand j-menu () ()
  (rofi:menu *menu* "-show-icons -theme gruvbox-dark-hard -cycle false"))

(defcommand j-menu-update () ()
  (j/load "menu"))
